import jwt from "jsonwebtoken";

const JWT_SECRET = process.env.JWT_SECRET;
const TOKEN_EXPIRATION = "1h";

function generateToken(payload){
    const jwtToken = jwt.sign(payload, JWT_SECRET, { expiresIn: TOKEN_EXPIRATION });
    return jwtToken;
}
/*
    Read jwt notes.
    sign(payload, secretKey, options)  => This method takes 3 args:
    1. Payload: an object containing mostly userId, name, roles allowed etc.. But not sensitive data like password, card numbers.
    2. secretKey: a string which always remains at server side only and used to sign the payload and generate token.
    3. Options: an object which can contain additional options like expiresIn, issuer, algorithm etc. These values will be added to payload or header of resulting jwt by sign() method and will be used while verifying the token.
    The sign() method will return a JWT token as string in formate: HEADER.PAYLOAD.SIGNATURE  (all in base64 encoded format, not by default encrypted).
    HEADER: contains metadata like which algo is used to generate the signature like: { "alg": "HS256", "typ": "JWT" } ==>
        By default 'jsonwebtoken' library uses 'HS256' algo to generate signature but we can choose our self as well by passing in options object like: { algorithm: "HS512", expiresIn: 1h }.
        Notice here algorithm will be added to header and 'expiresIn' will be added to payload. So it's not all values of options will be added to payload only.
    PAYLOAD: contains the payload we provided and also additional options like expiresIn, issuer etc.
    SIGNATURE: is generated by sign() method using the Header + payload and secretKey. This signature is used to verify the token.

    PLAYING WITH JWT TOKEN:
    console.log("JWT_SECRET: " + process.env.JWT_SECRET); // just to test if env variable is set or not, we will remove this later.
    const token = generateToken({userId: 202, role: "faltu"}); // giving payload only.
    console.log("in original form " + Buffer.from(token, "base64").toString("UTF-8")); // converting base64 encoded token to butter then to utf-8 string to see original form and we saw exactly like {"alg":"HS256","typ":"JWT"}.{"userId":202,"role":"faltu","iat":1697040000,"exp":1697068800}.<signature>
    console.log("token: " + token ); // just to test the token generation, we will remove this later.
*/

function verifyToken(token){
    return jwt.verify(token, JWT_SECRET); // on error it will throw error, so caller should wrap this in try-catch block to handle error.
}

/*
    verify(toke, secretKey)  => This method verifies the token client has returned is tempered or not, valid or expired...
    We pass client sent jwt token and our server side secretKey to verify().
    From client sent token it takes header + payload, generates signature using server side secretKey and compares it with the signature part of that token.
    If generated signature and signature present in that received token are not same means token is tempered and error will be thrown. That's why wrapped in try-catch block.
    Even if token is expired then also error will be thrown.
    Also It uses algo method mentioned in header of token to generate signature otherwise server have no idea which algo was used to generate that token.
*/

function temperingJwt(){
    console.log("JWT secret: " + process.env.JWT_SECRET);
    // generating a token:
    const token = generateToken({userId: 202, role: "faltu"});
    // logging token
    console.log("Generated token: " + token);
    // since it is in base64 encoded format, converting it into utf-8 to see original payload and header and signature.
    var tokenSplit = token.split(".");
    console.log("Printing token in original UTF-8 format: ");
    console.log("Header " + Buffer.from(tokenSplit[0], "base64url").toString("UTF-8") + " Payload " + Buffer.from(tokenSplit[1], "base64url").toString("UTF-8") + " Signature " + Buffer.from(tokenSplit[2], "base64url").toString("UTF-8"));

    // verifying 1st with same token:
    try{ console.log("Result of verification with original token: ", verifyToken(token))}catch(e){ console.log(e); }

    // now tempering token payload:
    var temperedPayload = {userId: 202, role: "admin"}; // changing role from 'faltu' to 'admin'
    // converting tempered payload into base64 encoded
    tokenSplit[1] = Buffer.from(JSON.stringify(temperedPayload), "UTF-8").toString("base64url");
    // forming the tempered token with [ same header + tempered payload + same signature ]
    const temperedToken = tokenSplit[0] + "." + tokenSplit[1] + "." + tokenSplit[2];
    // printing tempered token in original UTF-8 format:
    console.log("Printing tempered token in original UTF-8 format: ");
    console.log("Header " + Buffer.from(tokenSplit[0], "base64url").toString("UTF-8") + " Payload " + Buffer.from(tokenSplit[1], "base64url").toString("UTF-8") + " Signature " + Buffer.from(tokenSplit[2], "base64url").toString("UTF-8"));

    // verifying tempered token:
    try{ console.log("Result of verification with TEMPERED token: " + verifyToken(temperedToken)) }catch(e){ console.log( "Error because verify failed: " + e ); }
}

export { generateToken, verifyToken, temperingJwt };

/*
For JWT implementation we will use node's 'jsonwebtoken' library. It provides methods to sign and verify JWT tokens.
Now we need a secret key which will be used while creating and verifying the JWT token. This secret key always remains at server side only.
This secret key should not be hardcoded in code and never be commited to git.
So we have created a '.env' file at root of project and added that file to '.gitignore' and added variable JWT_SECRET="..."  in that '.env' file.

process.env
    ↓
A property of Node.js's global `process` object that provides access to environment variables available to the running Node.js process.
One way to provide environment variables from an environment file such as .env is using Node.js's ==>  --env-file=fileName command-line option.

While running the server we can use this option, like if I am doing ==>  node server.js   to start my server then
I can do ==>  node --env-file=.env server.js

Then if .env contains:
JWT_SECRET="..."
PORT=3000

We can access them:
process.env.JWT_SECRET
process.env.PORT

NOTE: '.env' in process.env  has nothing to do with our '.env' file.
process.env is a property of Node.js's 'process' object.
And if we print process.env,  then it will print all environment variables available to the running Node process, irrespective of
from which file they are coming from. It is a coincident that our file name is also '.env' containing environment variables.

*/